remote_theme: pages-themes/cayman@v0.2.0

#Setup
title: [Vixphy]
description: [Soluções de Computação em Nuvem]
show_downloads: false

google_analytics:
baseurl: ""
paginate: 1
values:
  layout: single