title:              Vixphy
email:              renato@vixphy.com.br
description:        Especialistas em nuvem
author:             Vixphy
baseurl:            ""
url:                "https://vixphy.com.br"

# Social Profiles
twitter_username:   vixphy
github_username:    vixphy
facebook_username:  vixphy
instagram_username: vixphy
linkedin_username:  company/vixphy-co

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
